export { connect } from './client'
export { default as config, type Config, configure } from '../config'
export { hook } from '../hooks'

export { default as ModelBackend } from './ModelBackend'
export { default as Aggregation } from './Aggregation'
export { default as QueryExecutor } from './QueryExecutor'
export { default as ChangeStream, type ChangeStreamOptions, type ChangeListener, type RawChangeListener, type ChangeListenerOptions } from './ChangeStream'
export { type ChangeStreamDocument, type ChangeStreamInsertDocument, type ChangeStreamUpdateDocument, type ChangeStreamDeleteDocument } from 'mongodb'
export { default as Cursor } from './Cursor'
export { default as Meta } from '../Meta'
export { default as ReferentialIntegrity, ReferentialIntegrityError, type Reference } from './ReferentialIntegrity'

export * from './admin'
export { type MongoClient } from 'mongodb'